#!/usr/bin/python3

import lifelib

from lifelib import Timeline, TimelineError, TimelineExit

import argparse
import sys


def parse_args():
  parser = argparse.ArgumentParser()
  group = parser.add_mutually_exclusive_group()
  group.add_argument("--start",
                     "-s",
                     metavar="ACTIVITY",
                     help="Start a new activity.")
  group.add_argument("--done",
                     "-d",
                     action="store_true",
                     help="Finish the current activity.")
  group.add_argument("--new",
                     "-n",
                     metavar="USER",
                     help="Create a new user & timeline.")
  group.add_argument("--default_user",
                     "-du",
                     action="store_true",
                     help="Check who the default user is.")
  group.add_argument("--set_default_user",
                     metavar="USER",
                     help="Change the default user.")
  group.add_argument("--create_category",
                     "-c",
                     metavar="CATEGORY_STRING",
                     help="Create a new leaf category. CATEGORY_STRING should "
                     "be in the format 'cat1/cat2/cat3'. If CATEGORY_STRING "
                     "has no instances of '/', the regular new category menu "
                     "will be invoked. Otherwise the path will be treated as "
                     "absolute and all non-existant categories in "
                     "CATEGORY_STRING will be created.")

  parser.add_argument("--user",
                      "-u",
                      metavar="USER",
                      help="Override the default user.")
  return parser.parse_args(sys.argv[1:])


def main():
  args = parse_args()

  timeline = Timeline(username=args.user)
  if args.start:
    timeline.start(args.start)
  elif args.done:
    activity, time_phrase = timeline.done()
    print(f"You spent {time_phrase} on '{activity}'")
  elif args.new:
    timeline_path = lifelib.new_timeline(args.new)
    print(f"Timeline created for {args.new} at '{timeline_path}'")
  elif args.default_user:
    print(lifelib.default_user())
  elif args.set_default_user:
    old_default_user = lifelib.default_user()
    lifelib.set_default_user(args.set_default_user)
    print(f"Changed default user from '{old_default_user}' to "
          f"'{args.set_default_user}'.")
  elif args.create_category:
    timeline.get_activity_id(args.create_category)
  else:
    timeline.print_status()

  timeline.save_timeline_to_file()


if __name__ == "__main__":
  print()

  try:
    main()
  except TimelineError as error:
    print(f"Error: {error}")
  except TimelineExit as error:
    print(f"Error: {error}")

  print()
